### ISSUE TITLE
Broken imports in spts_gui.py

### ISSUE THREAD

**Issue by FilipeMaia** [Toonggg/spts#4]
When I run spts_gui.py I get:

```$ spts_gui.py
Traceback (most recent call last):
  File "/Users/filipe/opt/miniconda3/envs/spts/bin/spts_gui.py", line 4, in <module>
    __import__('pkg_resources').run_script('spts==0.0.2', 'spts_gui.py')
  File "/Users/filipe/opt/miniconda3/envs/spts/lib/python3.8/site-packages/pkg_resources/__init__.py", line 665, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/filipe/opt/miniconda3/envs/spts/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1463, in run_script
    exec(code, namespace, namespace)
  File "/Users/filipe/opt/miniconda3/envs/spts/lib/python3.8/site-packages/spts-0.0.2-py3.8-macosx-10.9-x86_64.egg/EGG-INFO/scripts/spts_gui.py", line 3, in <module>
    import spts.gui.spts_gui
  File "/Users/filipe/opt/miniconda3/envs/spts/lib/python3.8/site-packages/spts-0.0.2-py3.8-macosx-10.9-x86_64.egg/spts/gui/spts_gui.py", line 18, in <module>
    import ui
ModuleNotFoundError: No module named 'ui'
```

**Comment by FilipeMaia** [comment]
#5 fixes it on my system.
